// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjFMXs4VpGHgK2Av2GGGmhqhwRYiL_dic',
    appId: '1:667052791950:web:7cd0b7f09512ae51f1d1df',
    messagingSenderId: '667052791950',
    projectId: 'android-cook-c74e8',
    authDomain: 'android-cook-c74e8.firebaseapp.com',
    storageBucket: 'android-cook-c74e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKG0Y9tUa6DWtUmjUqp1SeV6XJFXDBJEI',
    appId: '1:667052791950:android:af4cc8e95430aa7ef1d1df',
    messagingSenderId: '667052791950',
    projectId: 'android-cook-c74e8',
    storageBucket: 'android-cook-c74e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6T0FOQYVnMldZTuXO85XfZchQKSAqajo',
    appId: '1:667052791950:ios:ef0de0b62d70b2d4f1d1df',
    messagingSenderId: '667052791950',
    projectId: 'android-cook-c74e8',
    storageBucket: 'android-cook-c74e8.appspot.com',
    iosClientId: '667052791950-297nvudtedjftikksq690p5pmmp53cbe.apps.googleusercontent.com',
    iosBundleId: 'com.callor.cook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6T0FOQYVnMldZTuXO85XfZchQKSAqajo',
    appId: '1:667052791950:ios:e43fd16825b9fd62f1d1df',
    messagingSenderId: '667052791950',
    projectId: 'android-cook-c74e8',
    storageBucket: 'android-cook-c74e8.appspot.com',
    iosClientId: '667052791950-1k0am3squonmjl4bjv41663nhr2r4snn.apps.googleusercontent.com',
    iosBundleId: 'com.callor.cook.RunnerTests',
  );
}
